name: Flight Tracker Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # Executa a cada 5 minutos
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v4
    
    - name: Restaurar cache do banco de dados
      uses: actions/cache@v4
      with:
        path: flights.db
        key: flights-db-${{ github.run_id }}
        restore-keys: flights-db-
    
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_air.txt
        pip install FlightRadar24 || pip install git+https://github.com/JeanExtreme002/FlightRadarAPI.git
    - name: Executar o bot
      env:
        BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      run: python bot.py
    
    - name: Commit e push do banco de dados
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add flights.db
        git diff --quiet && git diff --staged --quiet || git commit -m "Update flight database"
        git push || echo "Nenhuma alteração para enviar"
